### ISSUE TITLE
[BUG] Seems he can't inject exe？

### ISSUE THREAD

**Issue by aadog** [oAGoulart/wrappem#13]
Seems he can't inject exe？

wrappem 1111.exe jiajuDLL.dll add ./dinput8.exe

![image](https://user-images.githubusercontent.com/18098725/163593457-332ae2c8-7ff2-4f6f-be92-a712e3623e3a.png)

**Comment by oAGoulart** [comment]
Hi there!

From what I've tested, if your executable has the standard [PE format ](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format) sections it should work just fine.
I will look more into it, could you send me the following info so I can help you:
- Which architecture are you targeting win32 or win64?
- Does your payload library `jiajuDLL.dll` have an entry point and the dummy function `add`? The payload library will be loaded as a normal DLL (which you can then use to hook the executable from the DLL entry point)
- Is this the only executable that doesn't work or none in your system does? If the last is true, could you send me a detailed overview of your system spec (including your windows specification)
- Could you send me the `1111.exe` and `jiajuDLL.dll` binaries and the generated output `dinput8.exe` to try and replicate this on my system? (if yes, send an attachment to josegoulart.aluno@unipampa.edu.br)
------
Thanks in advance!

**Comment by aadog** [comment]
Which architecture are you targeting win32 or win64?           win32

Is this the only executable that doesn't work or none in your system does? If the last is true, could you send me a detailed overview of your system spec (including your windows specification)     I am using win11 64 bit

Could you send me the 1111.exe and jiajuDLL.dll binaries and the generated output dinput8.exe to try and replicate this on my system? (if yes, send an attachment to josegoulart.aluno@unipampa.edu.br)

I'm about to send it to your mailbox, by the way this program has vmp

Maybe this is the reason for the injection failure? Clicking it after injection will report an error

**Comment by aadog** [comment]
Thank you for your reply

**Comment by aadog** [comment]
[1b2f3323.zip](https://github.com/oAGoulart/wrappem/files/8502057/1b2f3323.zip)

**Comment by aadog** [comment]
I tried sending it to your email, but it seems to be bounced

**Comment by aadog** [comment]
You are right, it looks like the problem is with the vmp

**Comment by aadog** [comment]
Thanks again
